Traceback (most recent call last):
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kda005\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt

# Create time values
t = np.linspace(0, 8 * np.pi, 1000) #eight cycles

#define frequencies, phases, and amplitudes of three sine waves
frequencies=np.array([1.,2.,4.])
phases=np.pi*np.array([1.,1./2,1./4])
amplitudes=np.array([1.,2.,4.])

# compute the wave signals
wave1 = amplitudes[0] * np.sin(2 * np.pi * frequencies[0] * t + phases[0])
wave2 = amplitudes[1] * np.sin(2 * np.pi * frequencies[1] * t + phases[1])
wave3 = amplitudes[2] * np.sin(2 * np.pi * frequencies[2] * t + phases[2])

#plot the wave signals
fig, ax = plt.subplots(2,1,shareX=True)
ax[0].set_xlim(( 0, 8*np.pi))
ax[0].set_ylim((-4, 4))

line1, = ax[0].plot(t, wave1, lw = 2, label='wave 1')
line2, = ax[0].plot(t, wave2, lw = 2, label='wave 2')
line3, = ax[0].plot(t, wave3, lw = 2, label='wave 3')

line4, = ax[1].plot(t, wave1+wave2+wave3, lw = 2, label='Superposition')

ax[0].set_ylabel('f')
ax[0].set_title("Initial Condition")
ax[0].legend()
ax[1].legend()
ax[1].set_xlabel('t')
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[1], line 18[0m
[0;32m     15[0m wave3 [38;5;241m=[39m amplitudes[[38;5;241m2[39m] [38;5;241m*[39m np[38;5;241m.[39msin([38;5;241m2[39m [38;5;241m*[39m np[38;5;241m.[39mpi [38;5;241m*[39m frequencies[[38;5;241m2[39m] [38;5;241m*[39m t [38;5;241m+[39m phases[[38;5;241m2[39m])
[0;32m     17[0m [38;5;66;03m#plot the wave signals[39;00m
[1;32m---> 18[0m fig, ax [38;5;241m=[39m [43mplt[49m[38;5;241;43m.[39;49m[43msubplots[49m[43m([49m[38;5;241;43m2[39;49m[43m,[49m[38;5;241;43m1[39;49m[43m,[49m[43mshareX[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m
[0;32m     19[0m ax[[38;5;241m0[39m][38;5;241m.[39mset_xlim(( [38;5;241m0[39m, [38;5;241m8[39m[38;5;241m*[39mnp[38;5;241m.[39mpi))
[0;32m     20[0m ax[[38;5;241m0[39m][38;5;241m.[39mset_ylim(([38;5;241m-[39m[38;5;241m4[39m, [38;5;241m4[39m))

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\pyplot.py:1613[0m, in [0;36msubplots[1;34m(nrows, ncols, sharex, sharey, squeeze, width_ratios, height_ratios, subplot_kw, gridspec_kw, **fig_kw)[0m
[0;32m   1459[0m [38;5;28;01mdef[39;00m [38;5;21msubplots[39m(
[0;32m   1460[0m     nrows: [38;5;28mint[39m [38;5;241m=[39m [38;5;241m1[39m, ncols: [38;5;28mint[39m [38;5;241m=[39m [38;5;241m1[39m, [38;5;241m*[39m,
[0;32m   1461[0m     sharex: [38;5;28mbool[39m [38;5;241m|[39m Literal[[38;5;124m"[39m[38;5;124mnone[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mall[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mrow[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mcol[39m[38;5;124m"[39m] [38;5;241m=[39m [38;5;28;01mFalse[39;00m,
[1;32m   (...)[0m
[0;32m   1468[0m     [38;5;241m*[39m[38;5;241m*[39mfig_kw
[0;32m   1469[0m ) [38;5;241m-[39m[38;5;241m>[39m [38;5;28mtuple[39m[Figure, Any]:
[0;32m   1470[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m   1471[0m [38;5;124;03m    Create a figure and a set of subplots.[39;00m
[0;32m   1472[0m 
[1;32m   (...)[0m
[0;32m   1611[0m 
[0;32m   1612[0m [38;5;124;03m    """[39;00m
[1;32m-> 1613[0m     fig [38;5;241m=[39m [43mfigure[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mfig_kw[49m[43m)[49m
[0;32m   1614[0m     axs [38;5;241m=[39m fig[38;5;241m.[39msubplots(nrows[38;5;241m=[39mnrows, ncols[38;5;241m=[39mncols, sharex[38;5;241m=[39msharex, sharey[38;5;241m=[39msharey,
[0;32m   1615[0m                        squeeze[38;5;241m=[39msqueeze, subplot_kw[38;5;241m=[39msubplot_kw,
[0;32m   1616[0m                        gridspec_kw[38;5;241m=[39mgridspec_kw, height_ratios[38;5;241m=[39mheight_ratios,
[0;32m   1617[0m                        width_ratios[38;5;241m=[39mwidth_ratios)
[0;32m   1618[0m     [38;5;28;01mreturn[39;00m fig, axs

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\pyplot.py:934[0m, in [0;36mfigure[1;34m(num, figsize, dpi, facecolor, edgecolor, frameon, FigureClass, clear, **kwargs)[0m
[0;32m    924[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(allnums) [38;5;241m==[39m max_open_warning [38;5;241m>[39m[38;5;241m=[39m [38;5;241m1[39m:
[0;32m    925[0m     _api[38;5;241m.[39mwarn_external(
[0;32m    926[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mMore than [39m[38;5;132;01m{[39;00mmax_open_warning[38;5;132;01m}[39;00m[38;5;124m figures have been opened. [39m[38;5;124m"[39m
[0;32m    927[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mFigures created through the pyplot interface [39m[38;5;124m"[39m
[1;32m   (...)[0m
[0;32m    931[0m         [38;5;124mf[39m[38;5;124m"[39m[38;5;124mConsider using `matplotlib.pyplot.close()`.[39m[38;5;124m"[39m,
[0;32m    932[0m         [38;5;167;01mRuntimeWarning[39;00m)
[1;32m--> 934[0m manager [38;5;241m=[39m [43mnew_figure_manager[49m[43m([49m
[0;32m    935[0m [43m    [49m[43mnum[49m[43m,[49m[43m [49m[43mfigsize[49m[38;5;241;43m=[39;49m[43mfigsize[49m[43m,[49m[43m [49m[43mdpi[49m[38;5;241;43m=[39;49m[43mdpi[49m[43m,[49m
[0;32m    936[0m [43m    [49m[43mfacecolor[49m[38;5;241;43m=[39;49m[43mfacecolor[49m[43m,[49m[43m [49m[43medgecolor[49m[38;5;241;43m=[39;49m[43medgecolor[49m[43m,[49m[43m [49m[43mframeon[49m[38;5;241;43m=[39;49m[43mframeon[49m[43m,[49m
[0;32m    937[0m [43m    [49m[43mFigureClass[49m[38;5;241;43m=[39;49m[43mFigureClass[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m    938[0m fig [38;5;241m=[39m manager[38;5;241m.[39mcanvas[38;5;241m.[39mfigure
[0;32m    939[0m [38;5;28;01mif[39;00m fig_label:

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\pyplot.py:465[0m, in [0;36mnew_figure_manager[1;34m(*args, **kwargs)[0m
[0;32m    463[0m [38;5;250m[39m[38;5;124;03m"""Create a new figure manager instance."""[39;00m
[0;32m    464[0m _warn_if_gui_out_of_main_thread()
[1;32m--> 465[0m [38;5;28;01mreturn[39;00m [43m_get_backend_mod[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mnew_figure_manager[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib_inline\backend_inline.py:27[0m, in [0;36mnew_figure_manager[1;34m(num, FigureClass, *args, **kwargs)[0m
[0;32m     21[0m [38;5;28;01mdef[39;00m [38;5;21mnew_figure_manager[39m(num, [38;5;241m*[39margs, FigureClass[38;5;241m=[39mFigure, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m     22[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m     23[0m [38;5;124;03m    Return a new figure manager for a new figure instance.[39;00m
[0;32m     24[0m 
[0;32m     25[0m [38;5;124;03m    This function is part of the API expected by Matplotlib backends.[39;00m
[0;32m     26[0m [38;5;124;03m    """[39;00m
[1;32m---> 27[0m     [38;5;28;01mreturn[39;00m new_figure_manager_given_figure(num, [43mFigureClass[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m)

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\figure.py:2494[0m, in [0;36mFigure.__init__[1;34m(self, figsize, dpi, facecolor, edgecolor, linewidth, frameon, subplotpars, tight_layout, constrained_layout, layout, **kwargs)[0m
[0;32m   2398[0m [38;5;28;01mdef[39;00m [38;5;21m__init__[39m([38;5;28mself[39m,
[0;32m   2399[0m              figsize[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[0;32m   2400[0m              dpi[38;5;241m=[39m[38;5;28;01mNone[39;00m,
[1;32m   (...)[0m
[0;32m   2410[0m              [38;5;241m*[39m[38;5;241m*[39mkwargs
[0;32m   2411[0m              ):
[0;32m   2412[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m   2413[0m [38;5;124;03m    Parameters[39;00m
[0;32m   2414[0m [38;5;124;03m    ----------[39;00m
[1;32m   (...)[0m
[0;32m   2492[0m [38;5;124;03m        %(Figure:kwdoc)s[39;00m
[0;32m   2493[0m [38;5;124;03m    """[39;00m
[1;32m-> 2494[0m     [38;5;28;43msuper[39;49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[38;5;21;43m__init__[39;49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m   2495[0m     [38;5;28mself[39m[38;5;241m.[39mfigure [38;5;241m=[39m [38;5;28mself[39m
[0;32m   2496[0m     [38;5;28mself[39m[38;5;241m.[39m_layout_engine [38;5;241m=[39m [38;5;28;01mNone[39;00m

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\figure.py:213[0m, in [0;36mFigureBase.__init__[1;34m(self, **kwargs)[0m
[0;32m    211[0m [38;5;28mself[39m[38;5;241m.[39mstale [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m    212[0m [38;5;28mself[39m[38;5;241m.[39msuppressComposite [38;5;241m=[39m [38;5;28;01mNone[39;00m
[1;32m--> 213[0m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mset[49m[43m([49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\artist.py:147[0m, in [0;36mArtist.__init_subclass__.<locals>.<lambda>[1;34m(self, **kwargs)[0m
[0;32m    139[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m([38;5;28mcls[39m[38;5;241m.[39mset, [38;5;124m'[39m[38;5;124m_autogenerated_signature[39m[38;5;124m'[39m):
[0;32m    140[0m     [38;5;66;03m# Don't overwrite cls.set if the subclass or one of its parents[39;00m
[0;32m    141[0m     [38;5;66;03m# has defined a set method set itself.[39;00m
[0;32m    142[0m     [38;5;66;03m# If there was no explicit definition, cls.set is inherited from[39;00m
[0;32m    143[0m     [38;5;66;03m# the hierarchy of auto-generated set methods, which hold the[39;00m
[0;32m    144[0m     [38;5;66;03m# flag _autogenerated_signature.[39;00m
[0;32m    145[0m     [38;5;28;01mreturn[39;00m
[1;32m--> 147[0m [38;5;28mcls[39m[38;5;241m.[39mset [38;5;241m=[39m [38;5;28;01mlambda[39;00m [38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs: [43mArtist[49m[38;5;241;43m.[39;49m[43mset[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[0;32m    148[0m [38;5;28mcls[39m[38;5;241m.[39mset[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124mset[39m[38;5;124m"[39m
[0;32m    149[0m [38;5;28mcls[39m[38;5;241m.[39mset[38;5;241m.[39m[38;5;18m__qualname__[39m [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mcls[39m[38;5;241m.[39m[38;5;18m__qualname__[39m[38;5;132;01m}[39;00m[38;5;124m.set[39m[38;5;124m"[39m

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\artist.py:1227[0m, in [0;36mArtist.set[1;34m(self, **kwargs)[0m
[0;32m   1223[0m [38;5;28;01mdef[39;00m [38;5;21mset[39m([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[0;32m   1224[0m     [38;5;66;03m# docstring and signature are auto-generated via[39;00m
[0;32m   1225[0m     [38;5;66;03m# Artist._update_set_signature_and_docstring() at the end of the[39;00m
[0;32m   1226[0m     [38;5;66;03m# module.[39;00m
[1;32m-> 1227[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_internal_update[49m[43m([49m[43mcbook[49m[38;5;241;43m.[39;49m[43mnormalize_kwargs[49m[43m([49m[43mkwargs[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[43m)[49m

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\artist.py:1219[0m, in [0;36mArtist._internal_update[1;34m(self, kwargs)[0m
[0;32m   1212[0m [38;5;28;01mdef[39;00m [38;5;21m_internal_update[39m([38;5;28mself[39m, kwargs):
[0;32m   1213[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[0;32m   1214[0m [38;5;124;03m    Update artist properties without prenormalizing them, but generating[39;00m
[0;32m   1215[0m [38;5;124;03m    errors as if calling `set`.[39;00m
[0;32m   1216[0m 
[0;32m   1217[0m [38;5;124;03m    The lack of prenormalization is to maintain backcompatibility.[39;00m
[0;32m   1218[0m [38;5;124;03m    """[39;00m
[1;32m-> 1219[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_update_props[49m[43m([49m
[0;32m   1220[0m [43m        [49m[43mkwargs[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;132;43;01m{cls.__name__}[39;49;00m[38;5;124;43m.set() got an unexpected keyword argument [39;49m[38;5;124;43m"[39;49m
[0;32m   1221[0m [43m        [49m[38;5;124;43m"[39;49m[38;5;132;43;01m{prop_name!r}[39;49;00m[38;5;124;43m"[39;49m[43m)[49m

File [1;32m~\Anaconda3\envs\GEOF211_compendium\Lib\site-packages\matplotlib\artist.py:1193[0m, in [0;36mArtist._update_props[1;34m(self, props, errfmt)[0m
[0;32m   1191[0m             func [38;5;241m=[39m [38;5;28mgetattr[39m([38;5;28mself[39m, [38;5;124mf[39m[38;5;124m"[39m[38;5;124mset_[39m[38;5;132;01m{[39;00mk[38;5;132;01m}[39;00m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[0;32m   1192[0m             [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mcallable[39m(func):
[1;32m-> 1193[0m                 [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[0;32m   1194[0m                     errfmt[38;5;241m.[39mformat([38;5;28mcls[39m[38;5;241m=[39m[38;5;28mtype[39m([38;5;28mself[39m), prop_name[38;5;241m=[39mk))
[0;32m   1195[0m             ret[38;5;241m.[39mappend(func(v))
[0;32m   1196[0m [38;5;28;01mif[39;00m ret:

[1;31mAttributeError[0m: Figure.set() got an unexpected keyword argument 'shareX'

