Traceback (most recent call last):
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/joao/opt/anaconda3/envs/teaching/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
N     = 30       # Number of time steps
M     = 100      # Number of space mesh points
c     = 0.75     # Propagation speed

dt = 0.01
dx = 1/M

print("Number of time steps = {:d}".format(N))
print("Number of grid points = {:d}".format(M))
print("Time step = {:f}".format(dt))
print("Grid size = {:f}".format(dx))
print("CFL number = {:f}".format(c*dt/dx))

# Grid points
X=np.linspace(0,1,M)

# Integrate the initial condition N time steps
U=upWind(topHat(X),c,dt,dx,N,M)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 15[0m
[1;32m     12[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mCFL number = [39m[38;5;132;01m{:f}[39;00m[38;5;124m"[39m[38;5;241m.[39mformat(c[38;5;241m*[39mdt[38;5;241m/[39mdx))
[1;32m     14[0m [38;5;66;03m# Grid points[39;00m
[0;32m---> 15[0m X[38;5;241m=[39m[43mnp[49m[38;5;241m.[39mlinspace([38;5;241m0[39m,[38;5;241m1[39m,M)
[1;32m     17[0m [38;5;66;03m# Integrate the initial condition N time steps[39;00m
[1;32m     18[0m U[38;5;241m=[39mupWind(topHat(X),c,dt,dx,N,M)

[0;31mNameError[0m: name 'np' is not defined
NameError: name 'np' is not defined

